server:
  port: 18091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.153.168
  rabbitmq:
    host: 192.168.153.168
    port: 5672
    virtual-host: /zch
    username: admin
    password: 123456
    publisher-confirm-type: correlated # SIMPLE-同步确认（阻塞） CORRELATED-异步确认
    publisher-returns: true # 确认消息是否到达队列
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
threadPool:
  coreSize: 100
  maxSize: 500
  keepAlive: 60
  blockingSize: 5000

